services:
  mysql:
    image: mysql:8.0
    container_name: gympro_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: gympro
      MYSQL_USER: gympro_user
      MYSQL_PASSWORD: gympro_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password --log-bin-trust-function-creators=1

volumes:
  mysql_data:
    driver: local
